//
//  Localization.swift
//  efe
//
//  Created by Artem Menshikov on 03.01.2026.
//

import Foundation

class Localization {
    static func localizedString(for key: String, language: Language) -> String {
        let translations: [Language: [String: String]] = [
            .russian: getRussianTranslations(),
            .english: getEnglishTranslations(),
            .french: getFrenchTranslations(),
            .spanish: getSpanishTranslations(),
            .chinese: getChineseTranslations(),
            .portuguese: getPortugueseTranslations(),
            .italian: getItalianTranslations()
        ]
        
        return translations[language]?[key] ?? key
    }
    
    private static func getRussianTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Выберите язык и тематику",
            "Базовый язык (с какого переводим)": "Базовый язык (с какого переводим)",
            "Язык для перевода": "Язык для перевода",
            "Выберите уровень сложности": "Выберите уровень сложности",
            "Показать перевод": "Показать перевод",
            "Примеры использования:": "Примеры использования:",
            "Нет элементов для изучения": "Нет элементов для изучения",
            "Изучение языков": "Изучение языков",
            "Начальный": "Начальный",
            "Средний": "Средний",
            "Продвинутый": "Продвинутый",
            "Базовые термины и понятия": "Базовые термины и понятия",
            "Профессиональная лексика": "Профессиональная лексика",
            "Сложные концепции и выражения": "Сложные концепции и выражения",
            "Настройки": "Настройки",
            "Закрыть": "Закрыть",
            "Сохранить": "Сохранить",
            "Настройки для категории:": "Настройки для категории:",
            "Настройки для всего приложения:": "Настройки для всего приложения:",
            "Частота напоминаний в день": "Частота напоминаний в день",
            "раз": "раз"
        ]
        
        // Категории
        let categories = [
            "Маркетинг": "Маркетинг",
            "Финансы": "Финансы",
            "Технологии": "Технологии",
            "Бизнес-стратегия": "Бизнес-стратегия",
            "Управление проектами": "Управление проектами",
            "Продажи": "Продажи",
            "HR и рекрутинг": "HR и рекрутинг",
            "Операции": "Операции",
            "Аналитика данных": "Аналитика данных",
            "Корпоративные финансы": "Корпоративные финансы",
            "Инвестиции": "Инвестиции",
            "Бухгалтерия": "Бухгалтерия",
            "Цифровой маркетинг": "Цифровой маркетинг",
            "Брендинг": "Брендинг",
            "Контент-маркетинг": "Контент-маркетинг",
            "SEO и SEM": "SEO и SEM",
            "Социальные медиа": "Социальные медиа",
            "E-commerce": "E-commerce",
            "Программирование": "Программирование",
            "Кибербезопасность": "Кибербезопасность",
            "Искусственный интеллект": "Искусственный интеллект",
            "Облачные технологии": "Облачные технологии",
            "Блокчейн": "Блокчейн",
            "Мобильная разработка": "Мобильная разработка",
            "Веб-разработка": "Веб-разработка",
            "DevOps": "DevOps",
            "Управление рисками": "Управление рисками",
            "Стратегическое планирование": "Стратегическое планирование",
            "Лидерство": "Лидерство",
            "Переговоры": "Переговоры",
            "Презентации": "Презентации",
            "Клиентский сервис": "Клиентский сервис",
            "Логистика": "Логистика",
            "Цепочка поставок": "Цепочка поставок",
            "Качество продукции": "Качество продукции",
            "Исследования рынка": "Исследования рынка",
            "Потребительское поведение": "Потребительское поведение",
            "Международный бизнес": "Международный бизнес",
            "Юридические вопросы": "Юридические вопросы",
            "Интеллектуальная собственность": "Интеллектуальная собственность",
            "Налогообложение": "Налогообложение",
            "Аудит": "Аудит",
            "Финансовое планирование": "Финансовое планирование",
            "Управление активами": "Управление активами",
            "Венчурный капитал": "Венчурный капитал",
            "Стартапы": "Стартапы",
            "Инновации": "Инновации",
            "Устойчивое развитие": "Устойчивое развитие",
            "Корпоративная этика": "Корпоративная этика",
            "Управление изменениями": "Управление изменениями",
            "Организационная культура": "Организационная культура",
            "Грамматика - Местоимения": "Грамматика - Местоимения",
            "Грамматика - Артикли": "Грамматика - Артикли",
            "Грамматика - Предлоги": "Грамматика - Предлоги",
            "Грамматика - Союзы": "Грамматика - Союзы",
            "Грамматика - Наречия": "Грамматика - Наречия",
            "Грамматика - Глаголы": "Грамматика - Глаголы",
            "Грамматика - Правила": "Грамматика - Правила"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getEnglishTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Choose language and topic",
            "Базовый язык (с какого переводим)": "Base language (from which we translate)",
            "Язык для перевода": "Language for translation",
            "Выберите уровень сложности": "Choose difficulty level",
            "Показать перевод": "Show translation",
            "Примеры использования:": "Usage examples:",
            "Нет элементов для изучения": "No items for study",
            "Изучение языков": "Language Learning",
            "Начальный": "Beginner",
            "Средний": "Intermediate",
            "Продвинутый": "Advanced",
            "Базовые термины и понятия": "Basic terms and concepts",
            "Профессиональная лексика": "Professional vocabulary",
            "Сложные концепции и выражения": "Complex concepts and expressions",
            "Настройки": "Settings",
            "Закрыть": "Close",
            "Сохранить": "Save",
            "Настройки для категории:": "Settings for category:",
            "Настройки для всего приложения:": "Settings for entire app:",
            "Частота напоминаний в день": "Reminder frequency per day",
            "раз": "times"
        ]
        
        let categories = [
            "Маркетинг": "Marketing",
            "Финансы": "Finance",
            "Технологии": "Technology",
            "Бизнес-стратегия": "Business Strategy",
            "Управление проектами": "Project Management",
            "Продажи": "Sales",
            "HR и рекрутинг": "HR and Recruiting",
            "Операции": "Operations",
            "Аналитика данных": "Data Analytics",
            "Корпоративные финансы": "Corporate Finance",
            "Инвестиции": "Investments",
            "Бухгалтерия": "Accounting",
            "Цифровой маркетинг": "Digital Marketing",
            "Брендинг": "Branding",
            "Контент-маркетинг": "Content Marketing",
            "SEO и SEM": "SEO and SEM",
            "Социальные медиа": "Social Media",
            "E-commerce": "E-commerce",
            "Программирование": "Programming",
            "Кибербезопасность": "Cybersecurity",
            "Искусственный интеллект": "Artificial Intelligence",
            "Облачные технологии": "Cloud Technologies",
            "Блокчейн": "Blockchain",
            "Мобильная разработка": "Mobile Development",
            "Веб-разработка": "Web Development",
            "DevOps": "DevOps",
            "Управление рисками": "Risk Management",
            "Стратегическое планирование": "Strategic Planning",
            "Лидерство": "Leadership",
            "Переговоры": "Negotiations",
            "Презентации": "Presentations",
            "Клиентский сервис": "Customer Service",
            "Логистика": "Logistics",
            "Цепочка поставок": "Supply Chain",
            "Качество продукции": "Product Quality",
            "Исследования рынка": "Market Research",
            "Потребительское поведение": "Consumer Behavior",
            "Международный бизнес": "International Business",
            "Юридические вопросы": "Legal Issues",
            "Интеллектуальная собственность": "Intellectual Property",
            "Налогообложение": "Taxation",
            "Аудит": "Audit",
            "Финансовое планирование": "Financial Planning",
            "Управление активами": "Asset Management",
            "Венчурный капитал": "Venture Capital",
            "Стартапы": "Startups",
            "Инновации": "Innovation",
            "Устойчивое развитие": "Sustainable Development",
            "Корпоративная этика": "Corporate Ethics",
            "Управление изменениями": "Change Management",
            "Организационная культура": "Organizational Culture",
            "Грамматика - Местоимения": "Grammar - Pronouns",
            "Грамматика - Артикли": "Grammar - Articles",
            "Грамматика - Предлоги": "Grammar - Prepositions",
            "Грамматика - Союзы": "Grammar - Conjunctions",
            "Грамматика - Наречия": "Grammar - Adverbs",
            "Грамматика - Глаголы": "Grammar - Verbs",
            "Грамматика - Правила": "Grammar - Rules"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getFrenchTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Choisissez la langue et le sujet",
            "Базовый язык (с какого переводим)": "Langue de base (de laquelle nous traduisons)",
            "Язык для перевода": "Langue pour la traduction",
            "Выберите уровень сложности": "Choisissez le niveau de difficulté",
            "Показать перевод": "Afficher la traduction",
            "Примеры использования:": "Exemples d'utilisation:",
            "Нет элементов для изучения": "Aucun élément à étudier",
            "Изучение языков": "Apprentissage des langues",
            "Начальный": "Débutant",
            "Средний": "Intermédiaire",
            "Продвинутый": "Avancé",
            "Базовые термины и понятия": "Termes et concepts de base",
            "Профессиональная лексика": "Vocabulaire professionnel",
            "Сложные концепции и выражения": "Concepts et expressions complexes",
            "Настройки": "Paramètres",
            "Закрыть": "Fermer",
            "Сохранить": "Enregistrer",
            "Настройки для категории:": "Paramètres pour la catégorie:",
            "Настройки для всего приложения:": "Paramètres pour toute l'application:",
            "Частота напоминаний в день": "Fréquence des rappels par jour",
            "раз": "fois"
        ]
        
        let categories = [
            "Маркетинг": "Marketing",
            "Финансы": "Finance",
            "Технологии": "Technologie",
            "Бизнес-стратегия": "Stratégie d'entreprise",
            "Управление проектами": "Gestion de projet",
            "Продажи": "Ventes",
            "HR и рекрутинг": "RH et recrutement",
            "Операции": "Opérations",
            "Аналитика данных": "Analyse de données",
            "Корпоративные финансы": "Finance d'entreprise",
            "Инвестиции": "Investissements",
            "Бухгалтерия": "Comptabilité",
            "Цифровой маркетинг": "Marketing numérique",
            "Брендинг": "Image de marque",
            "Контент-маркетинг": "Marketing de contenu",
            "SEO и SEM": "SEO et SEM",
            "Социальные медиа": "Médias sociaux",
            "E-commerce": "E-commerce",
            "Программирование": "Programmation",
            "Кибербезопасность": "Cybersécurité",
            "Искусственный интеллект": "Intelligence artificielle",
            "Облачные технологии": "Technologies cloud",
            "Блокчейн": "Blockchain",
            "Мобильная разработка": "Développement mobile",
            "Веб-разработка": "Développement web",
            "DevOps": "DevOps",
            "Управление рисками": "Gestion des risques",
            "Стратегическое планирование": "Planification stratégique",
            "Лидерство": "Leadership",
            "Переговоры": "Négociations",
            "Презентации": "Présentations",
            "Клиентский сервис": "Service client",
            "Логистика": "Logistique",
            "Цепочка поставок": "Chaîne d'approvisionnement",
            "Качество продукции": "Qualité des produits",
            "Исследования рынка": "Étude de marché",
            "Потребительское поведение": "Comportement du consommateur",
            "Международный бизнес": "Commerce international",
            "Юридические вопросы": "Questions juridiques",
            "Интеллектуальная собственность": "Propriété intellectuelle",
            "Налогообложение": "Fiscalité",
            "Аудит": "Audit",
            "Финансовое планирование": "Planification financière",
            "Управление активами": "Gestion d'actifs",
            "Венчурный капитал": "Capital-risque",
            "Стартапы": "Startups",
            "Инновации": "Innovation",
            "Устойчивое развитие": "Développement durable",
            "Корпоративная этика": "Éthique d'entreprise",
            "Управление изменениями": "Gestion du changement",
            "Организационная культура": "Culture organisationnelle",
            "Грамматика - Местоимения": "Grammaire - Pronoms",
            "Грамматика - Артикли": "Grammaire - Articles",
            "Грамматика - Предлоги": "Grammaire - Prépositions",
            "Грамматика - Союзы": "Grammaire - Conjonctions",
            "Грамматика - Наречия": "Grammaire - Adverbes",
            "Грамматика - Глаголы": "Grammaire - Verbes",
            "Грамматика - Правила": "Grammaire - Règles"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getSpanishTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Elige idioma y tema",
            "Базовый язык (с какого переводим)": "Idioma base (desde el cual traducimos)",
            "Язык для перевода": "Idioma para la traducción",
            "Выберите уровень сложности": "Elige el nivel de dificultad",
            "Показать перевод": "Mostrar traducción",
            "Примеры использования:": "Ejemplos de uso:",
            "Нет элементов для изучения": "No hay elementos para estudiar",
            "Изучение языков": "Aprendizaje de idiomas",
            "Начальный": "Principiante",
            "Средний": "Intermedio",
            "Продвинутый": "Avanzado",
            "Базовые термины и понятия": "Términos y conceptos básicos",
            "Профессиональная лексика": "Vocabulario profesional",
            "Сложные концепции и выражения": "Conceptos y expresiones complejas",
            "Настройки": "Configuración",
            "Закрыть": "Cerrar",
            "Сохранить": "Guardar",
            "Настройки для категории:": "Configuración para categoría:",
            "Настройки для всего приложения:": "Configuración para toda la aplicación:",
            "Частота напоминаний в день": "Frecuencia de recordatorios por día",
            "раз": "veces"
        ]
        
        let categories = [
            "Маркетинг": "Marketing",
            "Финансы": "Finanzas",
            "Технологии": "Tecnología",
            "Бизнес-стратегия": "Estrategia empresarial",
            "Управление проектами": "Gestión de proyectos",
            "Продажи": "Ventas",
            "HR и рекрутинг": "RRHH y reclutamiento",
            "Операции": "Operaciones",
            "Аналитика данных": "Análisis de datos",
            "Корпоративные финансы": "Finanzas corporativas",
            "Инвестиции": "Inversiones",
            "Бухгалтерия": "Contabilidad",
            "Цифровой маркетинг": "Marketing digital",
            "Брендинг": "Branding",
            "Контент-маркетинг": "Marketing de contenido",
            "SEO и SEM": "SEO y SEM",
            "Социальные медиа": "Redes sociales",
            "E-commerce": "E-commerce",
            "Программирование": "Programación",
            "Кибербезопасность": "Ciberseguridad",
            "Искусственный интеллект": "Inteligencia artificial",
            "Облачные технологии": "Tecnologías en la nube",
            "Блокчейн": "Blockchain",
            "Мобильная разработка": "Desarrollo móvil",
            "Веб-разработка": "Desarrollo web",
            "DevOps": "DevOps",
            "Управление рисками": "Gestión de riesgos",
            "Стратегическое планирование": "Planificación estratégica",
            "Лидерство": "Liderazgo",
            "Переговоры": "Negociaciones",
            "Презентации": "Presentaciones",
            "Клиентский сервис": "Servicio al cliente",
            "Логистика": "Logística",
            "Цепочка поставок": "Cadena de suministro",
            "Качество продукции": "Calidad del producto",
            "Исследования рынка": "Investigación de mercado",
            "Потребительское поведение": "Comportamiento del consumidor",
            "Международный бизнес": "Negocios internacionales",
            "Юридические вопросы": "Cuestiones legales",
            "Интеллектуальная собственность": "Propiedad intelectual",
            "Налогообложение": "Fiscalidad",
            "Аудит": "Auditoría",
            "Финансовое планирование": "Planificación financiera",
            "Управление активами": "Gestión de activos",
            "Венчурный капитал": "Capital riesgo",
            "Стартапы": "Startups",
            "Инновации": "Innovación",
            "Устойчивое развитие": "Desarrollo sostenible",
            "Корпоративная этика": "Ética corporativa",
            "Управление изменениями": "Gestión del cambio",
            "Организационная культура": "Cultura organizacional",
            "Грамматика - Местоимения": "Gramática - Pronombres",
            "Грамматика - Артикли": "Gramática - Artículos",
            "Грамматика - Предлоги": "Gramática - Preposiciones",
            "Грамматика - Союзы": "Gramática - Conjunciones",
            "Грамматика - Наречия": "Gramática - Adverbios",
            "Грамматика - Глаголы": "Gramática - Verbos",
            "Грамматика - Правила": "Gramática - Reglas"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getChineseTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "选择语言和主题",
            "Базовый язык (с какого переводим)": "基础语言（从哪种语言翻译）",
            "Язык для перевода": "翻译语言",
            "Выберите уровень сложности": "选择难度级别",
            "Показать перевод": "显示翻译",
            "Примеры использования:": "使用示例：",
            "Нет элементов для изучения": "没有学习项目",
            "Изучение языков": "语言学习",
            "Начальный": "初级",
            "Средний": "中级",
            "Продвинутый": "高级",
            "Базовые термины и понятия": "基本术语和概念",
            "Профессиональная лексика": "专业词汇",
            "Сложные концепции и выражения": "复杂的概念和表达",
            "Настройки": "设置",
            "Закрыть": "关闭",
            "Сохранить": "保存",
            "Настройки для категории:": "类别设置：",
            "Настройки для всего приложения:": "整个应用程序设置：",
            "Частота напоминаний в день": "每日提醒频率",
            "раз": "次"
        ]
        
        let categories = [
            "Маркетинг": "市场营销",
            "Финансы": "金融",
            "Технологии": "技术",
            "Бизнес-стратегия": "商业策略",
            "Управление проектами": "项目管理",
            "Продажи": "销售",
            "HR и рекрутинг": "人力资源和招聘",
            "Операции": "运营",
            "Аналитика данных": "数据分析",
            "Корпоративные финансы": "企业财务",
            "Инвестиции": "投资",
            "Бухгалтерия": "会计",
            "Цифровой маркетинг": "数字营销",
            "Брендинг": "品牌",
            "Контент-маркетинг": "内容营销",
            "SEO и SEM": "SEO和SEM",
            "Социальные медиа": "社交媒体",
            "E-commerce": "电子商务",
            "Программирование": "编程",
            "Кибербезопасность": "网络安全",
            "Искусственный интеллект": "人工智能",
            "Облачные технологии": "云计算技术",
            "Блокчейн": "区块链",
            "Мобильная разработка": "移动开发",
            "Веб-разработка": "网络开发",
            "DevOps": "DevOps",
            "Управление рисками": "风险管理",
            "Стратегическое планирование": "战略规划",
            "Лидерство": "领导力",
            "Переговоры": "谈判",
            "Презентации": "演示",
            "Клиентский сервис": "客户服务",
            "Логистика": "物流",
            "Цепочка поставок": "供应链",
            "Качество продукции": "产品质量",
            "Исследования рынка": "市场研究",
            "Потребительское поведение": "消费者行为",
            "Международный бизнес": "国际商务",
            "Юридические вопросы": "法律问题",
            "Интеллектуальная собственность": "知识产权",
            "Налогообложение": "税务",
            "Аудит": "审计",
            "Финансовое планирование": "财务规划",
            "Управление активами": "资产管理",
            "Венчурный капитал": "风险投资",
            "Стартапы": "初创企业",
            "Инновации": "创新",
            "Устойчивое развитие": "可持续发展",
            "Корпоративная этика": "企业伦理",
            "Управление изменениями": "变革管理",
            "Организационная культура": "组织文化",
            "Грамматика - Местоимения": "语法 - 代词",
            "Грамматика - Артикли": "语法 - 冠词",
            "Грамматика - Предлоги": "语法 - 介词",
            "Грамматика - Союзы": "语法 - 连词",
            "Грамматика - Наречия": "语法 - 副词",
            "Грамматика - Глаголы": "语法 - 动词",
            "Грамматика - Правила": "语法 - 规则"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getPortugueseTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Escolha o idioma e o tópico",
            "Базовый язык (с какого переводим)": "Idioma base (do qual traduzimos)",
            "Язык для перевода": "Idioma para tradução",
            "Выберите уровень сложности": "Escolha o nível de dificuldade",
            "Показать перевод": "Mostrar tradução",
            "Примеры использования:": "Exemplos de uso:",
            "Нет элементов для изучения": "Nenhum item para estudar",
            "Изучение языков": "Aprendizado de idiomas",
            "Начальный": "Iniciante",
            "Средний": "Intermediário",
            "Продвинутый": "Avançado",
            "Базовые термины и понятия": "Termos e conceitos básicos",
            "Профессиональная лексика": "Vocabulário profissional",
            "Сложные концепции и выражения": "Conceitos e expressões complexas",
            "Настройки": "Configurações",
            "Закрыть": "Fechar",
            "Сохранить": "Salvar",
            "Настройки для категории:": "Configurações para categoria:",
            "Настройки для всего приложения:": "Configurações para todo o aplicativo:",
            "Частота напоминаний в день": "Frequência de lembretes por dia",
            "раз": "vezes"
        ]
        
        let categories = [
            "Маркетинг": "Marketing",
            "Финансы": "Finanças",
            "Технологии": "Tecnologia",
            "Бизнес-стратегия": "Estratégia de negócios",
            "Управление проектами": "Gestão de projetos",
            "Продажи": "Vendas",
            "HR и рекрутинг": "RH e recrutamento",
            "Операции": "Operações",
            "Аналитика данных": "Análise de dados",
            "Корпоративные финансы": "Finanças corporativas",
            "Инвестиции": "Investimentos",
            "Бухгалтерия": "Contabilidade",
            "Цифровой маркетинг": "Marketing digital",
            "Брендинг": "Branding",
            "Контент-маркетинг": "Marketing de conteúdo",
            "SEO и SEM": "SEO e SEM",
            "Социальные медиа": "Mídias sociais",
            "E-commerce": "E-commerce",
            "Программирование": "Programação",
            "Кибербезопасность": "Cibersegurança",
            "Искусственный интеллект": "Inteligência artificial",
            "Облачные технологии": "Tecnologias em nuvem",
            "Блокчейн": "Blockchain",
            "Мобильная разработка": "Desenvolvimento móvel",
            "Веб-разработка": "Desenvolvimento web",
            "DevOps": "DevOps",
            "Управление рисками": "Gestão de riscos",
            "Стратегическое планирование": "Planejamento estratégico",
            "Лидерство": "Liderança",
            "Переговоры": "Negociações",
            "Презентации": "Apresentações",
            "Клиентский сервис": "Atendimento ao cliente",
            "Логистика": "Logística",
            "Цепочка поставок": "Cadeia de suprimentos",
            "Качество продукции": "Qualidade do produto",
            "Исследования рынка": "Pesquisa de mercado",
            "Потребительское поведение": "Comportamento do consumidor",
            "Международный бизнес": "Negócios internacionais",
            "Юридические вопросы": "Questões legais",
            "Интеллектуальная собственность": "Propriedade intelectual",
            "Налогообложение": "Tributação",
            "Аудит": "Auditoria",
            "Финансовое планирование": "Planejamento financeiro",
            "Управление активами": "Gestão de ativos",
            "Венчурный капитал": "Capital de risco",
            "Стартапы": "Startups",
            "Инновации": "Inovação",
            "Устойчивое развитие": "Desenvolvimento sustentável",
            "Корпоративная этика": "Ética corporativa",
            "Управление изменениями": "Gestão de mudanças",
            "Организационная культура": "Cultura organizacional",
            "Грамматика - Местоимения": "Gramática - Pronomes",
            "Грамматика - Артикли": "Gramática - Artigos",
            "Грамматика - Предлоги": "Gramática - Preposições",
            "Грамматика - Союзы": "Gramática - Conjunções",
            "Грамматика - Наречия": "Gramática - Advérbios",
            "Грамматика - Глаголы": "Gramática - Verbos",
            "Грамматика - Правила": "Gramática - Regras"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
    
    private static func getItalianTranslations() -> [String: String] {
        var dict: [String: String] = [
            "Выберите язык и тематику": "Scegli lingua e argomento",
            "Базовый язык (с какого переводим)": "Lingua base (da cui traduciamo)",
            "Язык для перевода": "Lingua per la traduzione",
            "Выберите уровень сложности": "Scegli il livello di difficoltà",
            "Показать перевод": "Mostra traduzione",
            "Примеры использования:": "Esempi di utilizzo:",
            "Нет элементов для изучения": "Nessun elemento da studiare",
            "Изучение языков": "Apprendimento delle lingue",
            "Начальный": "Principiante",
            "Средний": "Intermedio",
            "Продвинутый": "Avanzato",
            "Базовые термины и понятия": "Termini e concetti di base",
            "Профессиональная лексика": "Vocabolario professionale",
            "Сложные концепции и выражения": "Concetti ed espressioni complesse",
            "Настройки": "Impostazioni",
            "Закрыть": "Chiudi",
            "Сохранить": "Salva",
            "Настройки для категории:": "Impostazioni per categoria:",
            "Настройки для всего приложения:": "Impostazioni per l'intera app:",
            "Частота напоминаний в день": "Frequenza promemoria al giorno",
            "раз": "volte"
        ]
        
        let categories = [
            "Маркетинг": "Marketing",
            "Финансы": "Finanza",
            "Технологии": "Tecnologia",
            "Бизнес-стратегия": "Strategia aziendale",
            "Управление проектами": "Gestione progetti",
            "Продажи": "Vendite",
            "HR и рекрутинг": "HR e reclutamento",
            "Операции": "Operazioni",
            "Аналитика данных": "Analisi dati",
            "Корпоративные финансы": "Finanza aziendale",
            "Инвестиции": "Investimenti",
            "Бухгалтерия": "Contabilità",
            "Цифровой маркетинг": "Marketing digitale",
            "Брендинг": "Branding",
            "Контент-маркетинг": "Content marketing",
            "SEO и SEM": "SEO e SEM",
            "Социальные медиа": "Social media",
            "E-commerce": "E-commerce",
            "Программирование": "Programmazione",
            "Кибербезопасность": "Cybersicurezza",
            "Искусственный интеллект": "Intelligenza artificiale",
            "Облачные технологии": "Tecnologie cloud",
            "Блокчейн": "Blockchain",
            "Мобильная разработка": "Sviluppo mobile",
            "Веб-разработка": "Sviluppo web",
            "DevOps": "DevOps",
            "Управление рисками": "Gestione del rischio",
            "Стратегическое планирование": "Pianificazione strategica",
            "Лидерство": "Leadership",
            "Переговоры": "Negoziazioni",
            "Презентации": "Presentazioni",
            "Клиентский сервис": "Servizio clienti",
            "Логистика": "Logistica",
            "Цепочка поставок": "Catena di fornitura",
            "Качество продукции": "Qualità del prodotto",
            "Исследования рынка": "Ricerca di mercato",
            "Потребительское поведение": "Comportamento del consumatore",
            "Международный бизнес": "Business internazionale",
            "Юридические вопросы": "Questioni legali",
            "Интеллектуальная собственность": "Proprietà intellettuale",
            "Налогообложение": "Tassazione",
            "Аудит": "Audit",
            "Финансовое планирование": "Pianificazione finanziaria",
            "Управление активами": "Gestione patrimoniale",
            "Венчурный капитал": "Capitale di rischio",
            "Стартапы": "Startup",
            "Инновации": "Innovazione",
            "Устойчивое развитие": "Sviluppo sostenibile",
            "Корпоративная этика": "Etica aziendale",
            "Управление изменениями": "Gestione del cambiamento",
            "Организационная культура": "Cultura organizzativa",
            "Грамматика - Местоимения": "Grammatica - Pronomi",
            "Грамматика - Артикли": "Grammatica - Articoli",
            "Грамматика - Предлоги": "Grammatica - Preposizioni",
            "Грамматика - Союзы": "Grammatica - Congiunzioni",
            "Грамматика - Наречия": "Grammatica - Avverbi",
            "Грамматика - Глаголы": "Grammatica - Verbi",
            "Грамматика - Правила": "Grammatica - Regole"
        ]
        
        dict.merge(categories) { (_, new) in new }
        return dict
    }
}
